spring.application.name=api-training

# Configurações do Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/api-training
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desativa o mapeamento de recursos estáticos padrão para não "mascarar" erros
spring.web.resources.add-mappings=false